/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/SampleLevel.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function SampleLevel(props) {
  const { scene } = useGLTF('./models/SampleLevel.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group position={[0, 17, 0]} rotation={[0, 1.222, -0.803]} scale={2.5}>
        <directionalLight intensity={10} decay={2} rotation={[0, -Math.PI / 2, 0]} target={nodes.DirectionalLight_1.target}>
          <primitive object={nodes.DirectionalLight_1.target} position={[0, 0, -1]} />
        </directionalLight>
      </group>
      <group position={[-5, 4.7, -5.8]}>
        <group scale={0}>
          <PerspectiveCamera makeDefault={false} far={2000000} near={0.1} fov={58.716} rotation={[0, -Math.PI / 2, 0]} />
        </group>
      </group>
      <group position={[-5.614, 1.9, -5.635]} rotation={[0, -1.214, 0]}>
        <group scale={0}>
          <PerspectiveCamera makeDefault={false} far={2000000} near={0.1} fov={58.716} rotation={[0, -Math.PI / 2, 0]} />
        </group>
      </group>
      <group position={[-17.981, 1.607, -16.737]} rotation={[-0.014, -0.797, 0.119]}>
        <group scale={0}>
          <PerspectiveCamera makeDefault={false} far={2000000} near={0.1} fov={58.716} rotation={[0, -Math.PI / 2, 0]} />
        </group>
      </group>
      <group position={[16.997, 1.449, 17.219]} rotation={[Math.PI, 0.816, -2.956]}>
        <group scale={0}>
          <PerspectiveCamera makeDefault={false} far={2000000} near={0.1} fov={58.716} rotation={[0, -Math.PI / 2, 0]} />
        </group>
      </group>
      <group position={[-10.08, 2.99, 5.6]}>
        <mesh geometry={nodes.SkySphereMesh.geometry} material={materials.MID_M_Sky_Panning_Clouds2_0_SkySphereMesh} scale={400} />
      </group>
      <mesh geometry={nodes.Terrain.geometry} material={materials.Terrain} position={[-1.571, -0.076, -1.08]} />
      <group position={[10.5, -0.1, 0.1]} scale={0.5}>
        <mesh geometry={nodes.HillTree_02_1.geometry} material={materials.M_HillTree_01_Branches} />
        <mesh geometry={nodes.HillTree_02_2.geometry} material={materials.M_HillTree_01_Fronds} />
        <mesh geometry={nodes.HillTree_02_3.geometry} material={materials.M_HillTree_01_Branches} />
        <mesh geometry={nodes.HillTree_02_4.geometry} material={materials.M_HillTree_01_Leaves_HillTree_02} />
      </group>
      <group position={[-1.8, -0.1, 7.3]} rotation={[0, -Math.PI / 6, 0]} scale={0.5}>
        <mesh geometry={nodes.HillTree_3_1.geometry} material={materials.M_HillTree_01_Branches} />
        <mesh geometry={nodes.HillTree_3_2.geometry} material={materials.M_HillTree_01_Fronds} />
        <mesh geometry={nodes.HillTree_3_3.geometry} material={materials.M_HillTree_01_Branches} />
        <mesh geometry={nodes.HillTree_3_4.geometry} material={materials.M_HillTree_01_Leaves_HillTree_3} />
      </group>
      <group position={[-11.8, -0.1, 7.3]} rotation={[0, 1.222, 0]} scale={0.5}>
        <mesh geometry={nodes.HillTree_4_1.geometry} material={materials.M_HillTree_01_Branches} />
        <mesh geometry={nodes.HillTree_4_2.geometry} material={materials.M_HillTree_01_Fronds} />
        <mesh geometry={nodes.HillTree_4_3.geometry} material={materials.M_HillTree_01_Branches} />
        <mesh geometry={nodes.HillTree_4_4.geometry} material={materials.M_HillTree_01_Leaves_HillTree_4} />
      </group>
      <group position={[-2.183, -0.076, -4.991]}>
        <mesh geometry={nodes.Exterior_Walkways.geometry} material={materials.White} />
        <mesh geometry={nodes.Exterior_Walkways_1.geometry} material={materials.White} />
        <mesh geometry={nodes.Wall_003.geometry} material={materials.White} position={[0.229, 5.563, -1.575]} />
        <group position={[-7.752, 1.499, -4.268]}>
          <mesh geometry={nodes.Steps_1.geometry} material={materials.Iron__Ductile} />
          <mesh geometry={nodes.Steps_2.geometry} material={materials.Glass_Steps} />
        </group>
        <mesh geometry={nodes.CWall_001.geometry} material={materials.Aluminum} position={[0.229, 4.648, -2.108]} />
        <mesh geometry={nodes.CWall_002.geometry} material={materials.Aluminum} position={[0.229, 4.648, -2.108]} />
        <mesh geometry={nodes.CWall_003.geometry} material={materials.Aluminum} position={[0.229, 4.648, -2.108]} />
        <mesh geometry={nodes.CWall_004.geometry} material={materials.Aluminum} position={[0.229, 4.648, -2.108]} />
        <mesh geometry={nodes.CWall_005.geometry} material={materials.Aluminum} position={[0.229, 4.648, -2.108]} />
        <mesh geometry={nodes.CWall_006.geometry} material={materials.Aluminum} position={[0.229, 4.648, -2.108]} />
        <mesh geometry={nodes.CWall_007.geometry} material={materials.Aluminum} position={[0.229, 4.648, -2.108]} />
        <mesh geometry={nodes.CWall_008.geometry} material={materials.Aluminum} position={[0.229, 4.648, -2.108]} />
        <mesh geometry={nodes.CWall_009.geometry} material={materials.Aluminum} position={[0.229, 4.648, -2.108]} />
        <mesh geometry={nodes.CWall_010.geometry} material={materials.Aluminum} position={[0.229, 4.648, -2.108]} />
        <mesh geometry={nodes.Floor_1_1.geometry} material={materials.White} position={[0.229, 4.648, -2.134]} />
        <mesh geometry={nodes.Floor_2_1.geometry} material={materials.White} position={[0.229, 4.648, -2.134]} />
        <mesh geometry={nodes.Floor_2_2.geometry} material={materials.White} position={[0.229, 4.648, -2.134]} />
        <mesh geometry={nodes.Floor_2_3.geometry} material={materials.White} position={[0.229, 4.648, -2.134]} />
        <mesh geometry={nodes.Floor_2_4.geometry} material={materials.White} position={[0.229, 4.648, -2.134]} />
        <mesh geometry={nodes.Floor_4_1.geometry} material={materials.White} position={[0.229, 4.648, -2.134]} />
        <mesh geometry={nodes.Floor_4_2.geometry} material={materials.White} position={[0.229, 4.648, -2.134]} />
        <mesh geometry={nodes.Wall_001.geometry} material={materials.White} position={[0.229, 5.563, -1.575]} />
        <mesh geometry={nodes.Wall_002.geometry} material={materials.White} position={[0.229, 5.563, -1.575]} />
        <mesh geometry={nodes.Wall_005.geometry} material={materials.White} position={[0.229, 5.563, -1.575]} />
        <mesh geometry={nodes.Wall_006.geometry} material={materials.White} position={[0.229, 5.563, -1.575]} />
        <mesh geometry={nodes.Wall_007.geometry} material={materials.White} position={[0.229, 5.563, -1.575]} />
        <mesh geometry={nodes.Wall_008.geometry} material={materials.White} position={[0.229, 5.563, -1.575]} />
        <mesh geometry={nodes.Wall_009.geometry} material={materials.White} position={[0.229, 5.563, -1.575]} />
        <mesh geometry={nodes.BaseCol_007.geometry} material={materials.White} position={[-7.696, 0.076, -4.394]} />
        <mesh geometry={nodes.BaseCol_001.geometry} material={materials.White} position={[-5.715, 0.076, -4.394]} />
        <mesh geometry={nodes.BaseCol_002.geometry} material={materials.White} position={[-3.581, 0.076, -4.394]} />
        <mesh geometry={nodes.BaseCol_003.geometry} material={materials.White} position={[-0.533, 0.076, -4.394]} />
        <mesh geometry={nodes.BaseCol_004.geometry} material={materials.White} position={[2.464, 0.076, -10.566]} />
        <mesh geometry={nodes.BaseCol_005.geometry} material={materials.White} position={[6.02, 0.076, -10.566]} />
        <mesh geometry={nodes.BaseCol_006.geometry} material={materials.White} position={[9.576, 0.076, -10.566]} />
        <mesh geometry={nodes.TopCol_005.geometry} material={materials.White} position={[2.718, 7.391, 0.273]} />
        <mesh geometry={nodes.TopCol_001.geometry} material={materials.White} position={[3.772, 7.391, 0.273]} />
        <mesh geometry={nodes.TopCol_002.geometry} material={materials.White} position={[4.801, 7.391, 0.273]} />
        <mesh geometry={nodes.TopCol_003.geometry} material={materials.White} position={[4.801, 7.391, 2.038]} />
        <mesh geometry={nodes.TopCol_004.geometry} material={materials.White} position={[4.801, 7.391, 3.759]} />
        <group position={[-0.257, 2.132, -1.061]}>
          <mesh geometry={nodes.Railing_001_1.geometry} material={materials.Aluminum} />
          <mesh geometry={nodes.Railing_001_2.geometry} material={materials.Aluminum} />
        </group>
        <group position={[-0.257, 2.132, -1.061]}>
          <mesh geometry={nodes.Railing_002_1.geometry} material={materials.Iron__Ductile} />
          <mesh geometry={nodes.Railing_002_2.geometry} material={materials.Aluminum} />
        </group>
        <group position={[-0.257, 2.132, -1.061]}>
          <mesh geometry={nodes.Railing_003_1.geometry} material={materials.Iron__Ductile} />
          <mesh geometry={nodes.Railing_003_2.geometry} material={materials.Aluminum} />
        </group>
        <group position={[-0.257, 2.132, -1.061]}>
          <mesh geometry={nodes.Railing_004_1.geometry} material={materials.Iron__Ductile} />
          <mesh geometry={nodes.Railing_004_2.geometry} material={materials.Aluminum} />
        </group>
        <group position={[-0.257, 2.132, -1.061]}>
          <mesh geometry={nodes.Railing_005_1.geometry} material={materials.Iron__Ductile} />
          <mesh geometry={nodes.Railing_005_2.geometry} material={materials.Aluminum} />
        </group>
        <group position={[-0.257, 2.132, -1.061]}>
          <mesh geometry={nodes.Railing_006_1.geometry} material={materials.Aluminum} />
          <mesh geometry={nodes.Railing_006_2.geometry} material={materials.Aluminum} />
        </group>
        <group position={[-0.257, 2.132, -1.061]}>
          <mesh geometry={nodes.Railing_Stairs_001_1.geometry} material={materials.Iron__Ductile} />
          <mesh geometry={nodes.Railing_Stairs_001_2.geometry} material={materials.Aluminum} />
        </group>
        <group position={[-0.257, 2.132, -1.061]}>
          <mesh geometry={nodes.Railing_Stairs_002_1.geometry} material={materials.Aluminum} />
          <mesh geometry={nodes.Railing_Stairs_002_2.geometry} material={materials.Aluminum} />
        </group>
        <group position={[-5.531, 1.127, 4.181]} rotation={[-Math.PI, 0.873, -Math.PI]}>
          <mesh geometry={nodes.Door_01_L_1.geometry} material={materials.Aluminum} />
          <mesh geometry={nodes.Door_01_L_2.geometry} material={materials.MI_GlassWalls_Door_01_L} />
        </group>
        <group position={[-3.766, 1.127, 4.181]} rotation={[-Math.PI, -0.873, -Math.PI]}>
          <mesh geometry={nodes.Door_01_R_1.geometry} material={materials.Aluminum} />
          <mesh geometry={nodes.Door_01_R_2.geometry} material={materials.MI_GlassWalls_Door_01_R} />
        </group>
        <group position={[-5.683, 1.143, -6.487]}>
          <mesh geometry={nodes.Door_02_R_1.geometry} material={materials.Aluminum} />
          <mesh geometry={nodes.Door_02_R_2.geometry} material={materials.MI_GlassWalls_Door_02_R} />
        </group>
        <group position={[-3.613, 1.143, -6.487]}>
          <mesh geometry={nodes.Door_02_L_1.geometry} material={materials.Aluminum} />
          <mesh geometry={nodes.Door_02_L_2.geometry} material={materials.MI_GlassWalls_Door_02_L} />
        </group>
        <mesh geometry={nodes.CWall_Panels_013.geometry} material={materials.MI_GlassWalls_CWall_Panels_013} position={[-1.845, 1.616, -6.483]} />
        <mesh geometry={nodes.CWall_Panels_011.geometry} material={materials.MI_GlassWalls_CWall_Panels_011} position={[-7.452, 1.616, -6.483]} />
        <mesh geometry={nodes.CWall_Panels_002.geometry} material={materials.MI_GlassWalls_CWall_Panels_002} position={[-1.997, 1.616, 4.185]} />
        <mesh geometry={nodes.CWall_Panels_001.geometry} material={materials.MI_GlassWalls_CWall_Panels_001} position={[-7.275, 1.616, 4.185]} />
        <mesh geometry={nodes.CWall_Panels_2.geometry} material={materials.MI_GlassWalls_CWall_Panels_2} position={[-1.983, 1.616, 4.185]} />
        <mesh geometry={nodes.CWall_Panels_3.geometry} material={materials.MI_GlassWalls_CWall_Panels_3} position={[-4.653, 2.674, 4.185]} scale={[0.531, 0.313, 1]} />
        <mesh geometry={nodes.Stair_Panel_005.geometry} material={materials.MI_GlassWalls_Stair_Panel_005} position={[-8.038, 2.005, -4.649]} />
        <mesh geometry={nodes.Stair_Panel_004.geometry} material={materials.MI_GlassWalls_Stair_Panel_004} position={[-8.038, 2.516, -3.836]} />
        <mesh geometry={nodes.Stair_Panel_003.geometry} material={materials.MI_GlassWalls_Stair_Panel_003} position={[-8.038, 3.041, -3.023]} />
        <mesh geometry={nodes.CWall_Panels_021.geometry} material={materials.MI_GlassWalls_CWall_Panels_021} position={[-1.845, 4.648, -6.483]} />
        <mesh geometry={nodes.CWall_Panels_019.geometry} material={materials.MI_GlassWalls_CWall_Panels_019} position={[-7.452, 4.648, -6.483]} />
        <mesh geometry={nodes.CWall_Panels_005.geometry} material={materials.MI_GlassWalls_CWall_Panels_005} position={[-1.997, 4.648, 4.185]} />
        <mesh geometry={nodes.CWall_Panels_003.geometry} material={materials.MI_GlassWalls_CWall_Panels_003} position={[-7.317, 4.648, 4.185]} />
        <mesh geometry={nodes.CWall_Panels_004.geometry} material={materials.MI_GlassWalls_CWall_Panels_004} position={[-4.648, 4.648, 4.185]} />
        <mesh geometry={nodes.Stair_Panel_010.geometry} material={materials.MI_GlassWalls_Stair_Panel_010} position={[-8.895, 3.001, -3.15]} />
        <mesh geometry={nodes.Stair_Panel_009.geometry} material={materials.MI_GlassWalls_Stair_Panel_009} position={[-8.895, 2.475, -3.963]} />
        <mesh geometry={nodes.Stair_Panel_008.geometry} material={materials.MI_GlassWalls_Stair_Panel_008} position={[-8.895, 1.95, -4.776]} />
        <mesh geometry={nodes.CWall_Panels_017.geometry} material={materials.MI_GlassWalls_CWall_Panels_017} position={[-1.845, 7.68, -6.483]} />
        <mesh geometry={nodes.CWall_Panels_015.geometry} material={materials.MI_GlassWalls_CWall_Panels_015} position={[-7.452, 7.68, -6.483]} />
        <mesh geometry={nodes.CWall_Panels_008.geometry} material={materials.MI_GlassWalls_CWall_Panels_008} position={[-1.997, 7.68, 4.185]} />
        <mesh geometry={nodes.CWall_Panels_006.geometry} material={materials.MI_GlassWalls_CWall_Panels_006} position={[-7.299, 7.68, 4.185]} />
        <mesh geometry={nodes.CWall_Panels_067.geometry} material={materials.MI_GlassWalls_CWall_Panels_067} position={[2.33, 7.68, -9.195]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.CWall_Panels_059.geometry} material={materials.MI_GlassWalls_CWall_Panels_059} position={[2.33, 4.664, -9.195]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.CWall_Panels_007.geometry} material={materials.MI_GlassWalls_CWall_Panels_007} position={[-4.648, 7.68, 4.185]} />
        <mesh geometry={nodes.Railing_Panel_039.geometry} material={materials.MI_GlassRails_Railing_Panel_039} position={[-7.871, 3.524, -3.899]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Railing_Panel_038.geometry} material={materials.MI_GlassRails_Railing_Panel_038} position={[-7.871, 3.524, -3.086]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Railing_Panel_037.geometry} material={materials.MI_GlassRails_Railing_Panel_037} position={[-0.806, 3.524, -4.543]} />
        <mesh geometry={nodes.Railing_Panel_036.geometry} material={materials.MI_GlassRails_Railing_Panel_036} position={[-1.619, 3.524, -4.543]} />
        <mesh geometry={nodes.Railing_Panel_035.geometry} material={materials.MI_GlassRails_Railing_Panel_035} position={[-2.432, 3.524, -4.543]} />
        <mesh geometry={nodes.Railing_Panel_034.geometry} material={materials.MI_GlassRails_Railing_Panel_034} position={[-3.245, 3.524, -4.543]} />
        <mesh geometry={nodes.Railing_Panel_033.geometry} material={materials.MI_GlassRails_Railing_Panel_033} position={[-4.058, 3.524, -4.543]} />
        <mesh geometry={nodes.Railing_Panel_032.geometry} material={materials.MI_GlassRails_Railing_Panel_032} position={[-4.87, 3.524, -4.543]} />
        <mesh geometry={nodes.Railing_Panel_031.geometry} material={materials.MI_GlassRails_Railing_Panel_031} position={[-5.683, 3.524, -4.543]} />
        <mesh geometry={nodes.Railing_Panel_030.geometry} material={materials.MI_GlassRails_Railing_Panel_030} position={[-6.496, 3.524, -4.543]} />
        <mesh geometry={nodes.Railing_Panel_029.geometry} material={materials.MI_GlassRails_Railing_Panel_029} position={[-7.309, 3.524, -4.543]} />
        <mesh geometry={nodes.Railing_Panel_028.geometry} material={materials.MI_GlassRails_Railing_Panel_028} position={[8.531, 3.524, -1.309]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Railing_Panel_027.geometry} material={materials.MI_GlassRails_Railing_Panel_027} position={[8.531, 3.524, -0.496]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Railing_Panel_026.geometry} material={materials.MI_GlassRails_Railing_Panel_026} position={[8.531, 3.524, 0.316]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Railing_Panel_025.geometry} material={materials.MI_GlassRails_Railing_Panel_025} position={[8.531, 3.524, 1.129]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Railing_Panel_024.geometry} material={materials.MI_GlassRails_Railing_Panel_024} position={[8.531, 3.524, 1.942]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Railing_Panel_023.geometry} material={materials.MI_GlassRails_Railing_Panel_023} position={[8.531, 3.524, 2.755]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Railing_Panel_022.geometry} material={materials.MI_GlassRails_Railing_Panel_022} position={[8.531, 3.524, 3.568]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Railing_Panel_021.geometry} material={materials.MI_GlassRails_Railing_Panel_021} position={[7.963, 3.524, 3.984]} />
        <mesh geometry={nodes.Railing_Panel_020.geometry} material={materials.MI_GlassRails_Railing_Panel_020} position={[7.15, 3.524, 3.984]} />
        <mesh geometry={nodes.Railing_Panel_019.geometry} material={materials.MI_GlassRails_Railing_Panel_019} position={[6.338, 3.524, 3.984]} />
        <mesh geometry={nodes.Railing_Panel_018.geometry} material={materials.MI_GlassRails_Railing_Panel_018} position={[5.525, 3.524, 3.984]} />
        <mesh geometry={nodes.Railing_Panel_016.geometry} material={materials.MI_GlassRails_Railing_Panel_016} position={[3.176, 3.524, 0.178]} />
        <mesh geometry={nodes.Railing_Panel_015.geometry} material={materials.MI_GlassRails_Railing_Panel_015} position={[3.989, 3.524, 0.178]} />
        <mesh geometry={nodes.Railing_Panel_014.geometry} material={materials.MI_GlassRails_Railing_Panel_014} position={[0.738, 3.524, -1.561]} />
        <mesh geometry={nodes.Railing_Panel_013.geometry} material={materials.MI_GlassRails_Railing_Panel_013} position={[1.55, 3.524, -1.561]} />
        <mesh geometry={nodes.Railing_Panel_012.geometry} material={materials.MI_GlassRails_Railing_Panel_012} position={[1.55, 3.524, -0.19]} />
        <mesh geometry={nodes.Railing_Panel_011.geometry} material={materials.MI_GlassRails_Railing_Panel_011} position={[0.738, 3.524, -0.19]} />
        <mesh geometry={nodes.Railing_Panel_010.geometry} material={materials.MI_GlassRails_Railing_Panel_010} position={[-0.991, 3.524, 1.394]} />
        <mesh geometry={nodes.Railing_Panel_009.geometry} material={materials.MI_GlassRails_Railing_Panel_009} position={[-1.803, 3.524, 1.394]} />
        <mesh geometry={nodes.Railing_Panel_008.geometry} material={materials.MI_GlassRails_Railing_Panel_008} position={[-2.616, 3.524, 1.394]} />
        <mesh geometry={nodes.Railing_Panel_007.geometry} material={materials.MI_GlassRails_Railing_Panel_007} position={[-3.429, 3.524, 1.394]} />
        <mesh geometry={nodes.Railing_Panel_006.geometry} material={materials.MI_GlassRails_Railing_Panel_006} position={[-4.242, 3.524, 1.394]} />
        <mesh geometry={nodes.Railing_Panel_005.geometry} material={materials.MI_GlassRails_Railing_Panel_005} position={[-5.055, 3.524, 1.394]} />
        <mesh geometry={nodes.Railing_Panel_004.geometry} material={materials.MI_GlassRails_Railing_Panel_004} position={[-5.867, 3.524, 1.394]} />
        <mesh geometry={nodes.Railing_Panel_003.geometry} material={materials.MI_GlassRails_Railing_Panel_003} position={[-6.68, 3.524, 1.394]} />
        <mesh geometry={nodes.Railing_Panel_002.geometry} material={materials.MI_GlassRails_Railing_Panel_002} position={[-7.493, 3.524, 1.394]} />
        <mesh geometry={nodes.Railing_Panel_001.geometry} material={materials.MI_GlassRails_Railing_Panel_001} position={[-8.306, 3.524, 1.394]} />
        <mesh geometry={nodes.CWall_Panels_009.geometry} material={materials.MI_GlassWalls_CWall_Panels_009} position={[-4.648, 2.667, 4.185]} />
        <mesh geometry={nodes.CWall_Panels_018.geometry} material={materials.MI_GlassWalls_CWall_Panels_018} position={[-9.252, 7.68, -5.537]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.CWall_Panels_014.geometry} material={materials.MI_GlassWalls_CWall_Panels_014} position={[-0.044, 7.68, -5.537]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes.CWall_Panels_012.geometry} material={materials.MI_GlassWalls_CWall_Panels_012} position={[-0.044, 1.616, -5.537]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes.CWall_Panels_010.geometry} material={materials.MI_GlassWalls_CWall_Panels_010} position={[-9.252, 1.616, -5.537]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Stair_Panel_002.geometry} material={materials.MI_GlassWalls_Stair_Panel_002} position={[-7.317, 2.119, -3.846]} />
        <mesh geometry={nodes.CWall_Panels_064.geometry} material={materials.MI_GlassWalls_CWall_Panels_064} position={[6.02, 7.68, -10.751]} />
        <mesh geometry={nodes.CWall_Panels_057.geometry} material={materials.MI_GlassWalls_CWall_Panels_057} position={[6.02, 4.664, -10.751]} />
        <mesh geometry={nodes.CWall_Panels_068.geometry} material={materials.MI_GlassWalls_CWall_Panels_068} position={[2.33, 7.68, -10.398]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.CWall_Panels_066.geometry} material={materials.MI_GlassWalls_CWall_Panels_066} position={[2.33, 7.68, -7.991]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.CWall_Panels_065.geometry} material={materials.MI_GlassWalls_CWall_Panels_065} position={[9.357, 7.68, -10.751]} />
        <mesh geometry={nodes.CWall_Panels_063.geometry} material={materials.MI_GlassWalls_CWall_Panels_063} position={[2.683, 7.68, -10.751]} />
        <mesh geometry={nodes.CWall_Panels_062.geometry} material={materials.MI_GlassWalls_CWall_Panels_062} position={[9.709, 7.68, -6.467]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes.CWall_Panels_060.geometry} material={materials.MI_GlassWalls_CWall_Panels_060} position={[9.709, 7.68, -10.398]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes.CWall_Panels_058.geometry} material={materials.MI_GlassWalls_CWall_Panels_058} position={[2.33, 4.664, -10.398]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.CWall_Panels_056.geometry} material={materials.MI_GlassWalls_CWall_Panels_056} position={[9.357, 4.664, -10.751]} />
        <mesh geometry={nodes.CWall_Panels_054.geometry} material={materials.MI_GlassWalls_CWall_Panels_054} position={[9.709, 4.664, -6.467]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes.CWall_Panels_053.geometry} material={materials.MI_GlassWalls_CWall_Panels_053} position={[9.709, 4.664, -10.398]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes.CWall_Panels_052.geometry} material={materials.MI_GlassWalls_CWall_Panels_052} position={[2.683, 4.664, -10.751]} />
        <mesh geometry={nodes.CWall_Panels_051.geometry} material={materials.MI_GlassWalls_CWall_Panels_051} position={[2.33, 4.664, -7.991]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.CWall_Panels_050.geometry} material={materials.MI_GlassWalls_CWall_Panels_050} position={[9.646, 7.68, -1.407]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.CWall_Panels_047.geometry} material={materials.MI_GlassWalls_CWall_Panels_047} position={[9.646, 7.68, 6.182]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.CWall_Panels_046.geometry} material={materials.MI_GlassWalls_CWall_Panels_046} position={[9.357, 7.68, 6.471]} />
        <mesh geometry={nodes.CWall_Panels_044.geometry} material={materials.MI_GlassWalls_CWall_Panels_044} position={[5.121, 7.68, 6.471]} />
        <mesh geometry={nodes.CWall_Panels_043.geometry} material={materials.MI_GlassWalls_CWall_Panels_043} position={[4.832, 7.68, 6.182]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes.CWall_Panels_031.geometry} material={materials.MI_GlassWalls_CWall_Panels_031} position={[9.646, 1.616, -1.407]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.CWall_Panels_029.geometry} material={materials.MI_GlassWalls_CWall_Panels_029} position={[9.357, 1.616, 6.471]} />
        <mesh geometry={nodes.CWall_Panels_027.geometry} material={materials.MI_GlassWalls_CWall_Panels_027} position={[4.832, 1.616, 6.182]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes.CWall_Panels_026.geometry} material={materials.MI_GlassWalls_CWall_Panels_026} position={[9.646, 1.616, 6.182]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.CWall_Panels_025.geometry} material={materials.MI_GlassWalls_CWall_Panels_025} position={[5.121, 1.616, 6.471]} />
        <mesh geometry={nodes.CWall_Panels_069.geometry} material={materials.MI_GlassWalls_CWall_Panels_069} position={[-4.648, 2.683, -6.483]} />
        <mesh geometry={nodes.CWall_Panels_016.geometry} material={materials.MI_GlassWalls_CWall_Panels_016} position={[-4.648, 7.68, -6.483]} />
        <mesh geometry={nodes.Stair_Panel_007.geometry} material={materials.MI_GlassWalls_Stair_Panel_007} position={[-7.279, 1.053, -6.106]} />
        <mesh geometry={nodes.CWall_Panels_042.geometry} material={materials.MI_GlassWalls_CWall_Panels_042} position={[4.832, 7.68, 4.994]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes.CWall_Panels_024.geometry} material={materials.MI_GlassWalls_CWall_Panels_024} position={[4.832, 1.616, 4.994]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes.Stair_Panel_006.geometry} material={materials.MI_GlassWalls_Stair_Panel_006} position={[-8.438, 1.543, -6.106]} />
        <mesh geometry={nodes.CWall_Panels_020.geometry} material={materials.MI_GlassWalls_CWall_Panels_020} position={[-4.648, 4.648, -6.483]} />
        <mesh geometry={nodes.Stair_Panel_001.geometry} material={materials.MI_GlassWalls_Stair_Panel_001} position={[-7.279, 1.053, -5.249]} />
        <mesh geometry={nodes.CWall_Panels_023.geometry} material={materials.MI_GlassWalls_CWall_Panels_023} position={[-0.044, 4.648, -5.537]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes.CWall_Panels_022.geometry} material={materials.MI_GlassWalls_CWall_Panels_022} position={[-9.252, 4.648, -5.537]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.CWall_Panels_040.geometry} material={materials.MI_GlassWalls_CWall_Panels_040} position={[4.832, 4.648, 4.994]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes.CWall_Panels_041.geometry} material={materials.MI_GlassWalls_CWall_Panels_041} position={[4.832, 4.648, 6.182]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes.CWall_Panels_039.geometry} material={materials.MI_GlassWalls_CWall_Panels_039} position={[9.646, 4.648, -1.407]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.CWall_Panels_036.geometry} material={materials.MI_GlassWalls_CWall_Panels_036} position={[9.646, 4.648, 6.182]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.CWall_Panels_035.geometry} material={materials.MI_GlassWalls_CWall_Panels_035} position={[9.357, 4.648, 6.471]} />
        <mesh geometry={nodes.CWall_Panels_033.geometry} material={materials.MI_GlassWalls_CWall_Panels_033} position={[5.121, 4.648, 6.471]} />
        <mesh geometry={nodes.CWall_Panels_049.geometry} material={materials.MI_GlassWalls_CWall_Panels_049} position={[9.646, 7.68, 0.635]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.CWall_Panels_048.geometry} material={materials.MI_GlassWalls_CWall_Panels_048} position={[9.646, 7.68, 4.14]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.CWall_Panels_032.geometry} material={materials.MI_GlassWalls_CWall_Panels_032} position={[9.646, 1.616, 0.635]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.CWall_Panels_030.geometry} material={materials.MI_GlassWalls_CWall_Panels_030} position={[9.646, 1.616, 4.14]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.CWall_Panels_038.geometry} material={materials.MI_GlassWalls_CWall_Panels_038} position={[9.646, 4.648, 0.635]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.CWall_Panels_037.geometry} material={materials.MI_GlassWalls_CWall_Panels_037} position={[9.646, 4.648, 4.14]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.CWall_Panels_045.geometry} material={materials.MI_GlassWalls_CWall_Panels_045} position={[7.239, 7.68, 6.471]} />
        <mesh geometry={nodes.CWall_Panels_028.geometry} material={materials.MI_GlassWalls_CWall_Panels_028} position={[7.239, 1.616, 6.471]} />
        <mesh geometry={nodes.CWall_Panels_061.geometry} material={materials.MI_GlassWalls_CWall_Panels_061} position={[9.709, 7.68, -8.433]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes.CWall_Panels_055.geometry} material={materials.MI_GlassWalls_CWall_Panels_055} position={[9.709, 4.664, -8.433]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes.CWall_Panels_034.geometry} material={materials.MI_GlassWalls_CWall_Panels_034} position={[7.239, 4.648, 6.471]} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/SampleLevel.glb')
